# 집계처리 Aggregation
- 집계함수
- groupby()
- pivot_table()

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'name': ['김혜수', '박보검', '송혜교', '아이유', '공유', '전지현', '수지', '유재석', '강동원', '윤아'],
    'department': ['인사', '재무', '재무', 'IT', 'IT', '인사', '재무', '인사', 'IT', '재무'],
    'job': ['사원', '과장', '대리', '사원', '팀장', '대리', '대리', '과장', '사원', '팀장'],
    'branch': ['서울', '부산', '서울', '부산', '서울', '서울', '서울', '부산', '서울', '부산'],
    'salary': [3500, 5000, 4200, 3800, 6000, 4500, 4600, 5200, 3900, 6100],
    'hire_date': ['2020-03-15', '2018-07-10', '2019-05-20', '2021-01-10', '2017-09-25', '2019-03-05', '2020-06-12', '2016-11-30', '2022-04-01', '2017-12-15']
}
emp_df = pd.DataFrame(data)

# 문자열 타입의 날짜를 pandas가 계산할 수 있는 날짜 타입(datetime)으로 변환
emp_df['hire_date'] = pd.to_datetime(emp_df['hire_date'])
emp_df

  name department job branch  salary  hire_date
0  김혜수         인사  사원     서울    3500 2020-03-15
1  박보검         재무  과장     부산    5000 2018-07-10
2  송혜교         재무  대리     서울    4200 2019-05-20
3  아이유         IT  사원     부산    3800 2021-01-10
4   공유         IT  팀장     서울    6000 2017-09-25
5  전지현         인사  대리     서울    4500 2019-03-05
6   수지         재무  대리     서울    4600 2020-06-12
7  유재석         인사  과장     부산    5200 2016-11-30
8  강동원         IT  사원     서울    3900 2022-04-01
9   윤아         재무  팀장     부산    6100 2017-12-15

In [3]:
emp_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        10 non-null     str
 1   department  10 non-null     str
 2   job         10 non-null     str
 3   branch      10 non-null     str
 4   salary      10 non-null     int64
 5   hire_date   10 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 861.0 bytes

In [6]:
display(emp_df.describe(include='all')) # 모든 컬럼
display(emp_df.describe(include='str')) # 특정 자료형 컬럼

       name department  job branch       salary            hire_date
count    10         10   10     10    10.000000                   10
unique   10          3    4      2          NaN                  NaN
top     김혜수         재무   사원     서울          NaN                  NaN
freq      1          4    3      6          NaN                  NaN
mean    NaN        NaN  NaN    NaN  4680.000000  2019-05-12 07:12:00
min     NaN        NaN  NaN    NaN  3500.000000  2016-11-30 00:00:00
25%     NaN        NaN  NaN    NaN  3975.000000  2018-02-04 18:00:00
50%     NaN        NaN  NaN    NaN  4550.000000  2019-04-12 00:00:00
75%     NaN        NaN  NaN    NaN  5150.000000  2020-05-20 18:00:00
max     NaN        NaN  NaN    NaN  6100.000000  2022-04-01 00:00:00
std     NaN        NaN  NaN    NaN   892.935235                  NaN

       name department job branch
count    10         10  10     10
unique   10          3   4      2
top     김혜수         재무  사원     서울
freq      1          4   3      6

## 집계함수

In [7]:
print('count: ', emp_df['salary'].count())
print('min: ', emp_df['salary'].min())
print('max: ', emp_df['salary'].max())
print('mean: ', emp_df['salary'].mean())
print('var: ', emp_df['salary'].var())
print('std: ', emp_df['salary'].std())
print('median: ', emp_df['salary'].median())

count:  10
min:  3500
max:  6100
mean:  4680.0
var:  797333.3333333334
std:  892.9352346801718
median:  4550.0

In [8]:
# 사분위수 : 데이터를 오름차순 정렬 후 4등분하는 기준 값
print('0%:', emp_df['salary'].quantile(0))
print('25%:', emp_df['salary'].quantile(0.25))
print('50%:', emp_df['salary'].quantile(0.5))
print('75%:', emp_df['salary'].quantile(0.75))
print('100%:', emp_df['salary'].quantile(1))

0%: 3500.0
25%: 3975.0
50%: 4550.0
75%: 5150.0
100%: 6100.0

## groupby
- 데이터를 특정 기준에 따라 그룹화하여 집계 연산을 수행
- 컬럼을 기준으로 그룹화하여 집계 연산을 수행

In [11]:
dept = emp_df.groupby('department')
print(type(dept))
print(dept)

<class 'pandas.api.typing.DataFrameGroupBy'>
<pandas.api.typing.DataFrameGroupBy object at 0x0000020DE5677EF0>

In [12]:
dept.groups # 그룹별 행 인덱스 반환

{'IT': [3, 4, 8], '인사': [0, 5, 7], '재무': [1, 2, 6, 9]}

In [15]:
dept_salary = emp_df.groupby('department')['salary']
print("부서별 평균 급여")
print(dept_salary.mean())

print("부서별 최소 급여")
print(dept_salary.min())

print("부서별 최대 급여")
print(dept_salary.max())

부서별 평균 급여
department
IT    4566.666667
인사    4400.000000
재무    4975.000000
Name: salary, dtype: float64
부서별 최소 급여
department
IT    3800
인사    3500
재무    4200
Name: salary, dtype: int64
부서별 최대 급여
department
IT    6000
인사    5200
재무    6100
Name: salary, dtype: int64

In [18]:
# 직급별 인원수 조회
print(emp_df.groupby('job')['name'].count())
print(emp_df['job'].value_counts())

job
과장    2
대리    3
사원    3
팀장    2
Name: name, dtype: int64
job
사원    3
대리    3
과장    2
팀장    2
Name: count, dtype: int64

In [19]:
# 부서별 연봉그룹별 인원수 조회
# - 3000~4000, 4000~5000, 5000이상
# - 연봉그룹컬럼을 생성후 그룹핑
def set_salary_group(salary):
    if 3000 <= salary < 4000:
        return '3000대'
    elif 4000 <= salary < 5000:
        return '4000대'
    else:
        return '5000대이상'

# apply(함수): df, ser의 각 요소에 함수를 적용
emp_df['salary_group'] = emp_df['salary'].apply(set_salary_group)
# print(emp_df) #salary_group 컬럼 추가 확인

print(emp_df.groupby(['department', 'salary_group'])['name'].count())
print(emp_df[['department', 'salary_group']].value_counts())

department  salary_group
IT          3000대           2
            5000대이상         1
인사          3000대           1
            4000대           1
            5000대이상         1
재무          4000대           2
            5000대이상         2
Name: name, dtype: int64
department  salary_group
재무          5000대이상         2
            4000대           2
IT          3000대           2
인사          3000대           1
IT          5000대이상         1
인사          4000대           1
            5000대이상         1
Name: count, dtype: int64

In [20]:
# agg 집계함수 모음
# - 그룹화된 데이터에서 원하는 집계 연산을 적용하여 요약 통계를 반환
emp_df.groupby('department')['salary'].agg(['count', 'mean', 'max', 'min', 'std'])

            count         mean   max   min          std
department
IT              3  4566.666667  6000  3800  1242.309677
인사              3  4400.000000  5200  3500   854.400375
재무              4  4975.000000  6100  4200   818.026079

In [21]:
emp_df.groupby('department').agg({
    'salary': 'mean',
    'hire_date': 'min'
})

                 salary  hire_date
department
IT          4566.666667 2017-09-25
인사          4400.000000 2016-11-30
재무          4975.000000 2017-12-15

In [22]:
dept_salary_df = emp_df.groupby("department", as_index=False).agg(
    employee_count=("name", "count"),
    avg_salary=("salary", "mean"),
    min_salary=("salary", "min"),
    max_salary=("salary", "max")
)

dept_salary_df["avg_salary"] = dept_salary_df["avg_salary"].round(1)
display(dept_salary_df)

  department  employee_count  avg_salary  min_salary  max_salary
0         IT               3      4566.7        3800        6000
1         인사               3      4400.0        3500        5200
2         재무               4      4975.0        4200        6100

In [24]:
# filter() : 그룹에 대한 조건을 기준으로 그룹 전체를 남김
# == 그룹 필터링

# 부서 급여 평균이 4500 초과인 부서만 출력
(emp_df.groupby('department').filter(
    lambda group: group['salary'].mean() > 4500)
)

  name department job branch  salary  hire_date salary_group
1  박보검         재무  과장     부산    5000 2018-07-10      5000대이상
2  송혜교         재무  대리     서울    4200 2019-05-20        4000대
3  아이유         IT  사원     부산    3800 2021-01-10        3000대
4   공유         IT  팀장     서울    6000 2017-09-25      5000대이상
6   수지         재무  대리     서울    4600 2020-06-12        4000대
8  강동원         IT  사원     서울    3900 2022-04-01        3000대
9   윤아         재무  팀장     부산    6100 2017-12-15      5000대이상

## pivot_table
- 기본 기능: 데이터를 행, 열, 값으로 재구성하여 테이블을 만든다.
- 사용 방식: 단순히 재구성하려는 index, columns, values를 지정한다.
- 중복 허용: 동일한 index와 columns 조합이 중복될 경우, aggfunc를 통해 해당 중복된 데이터를 집계할 수 있다.
- 집계 함수 지원: aggfunc 매개변수를 사용하여 sum, mean, count 등의 집계 함수를 적용할 수 있다. (기본값: mean)
- 결측치 채움: fill_value 매개변수를 사용하여 결측치를 채울 수 있다.

In [25]:
data = {
    '날짜': [
        '2024-01-01', '2024-01-01', '2024-01-01', '2024-01-01',
        '2024-01-02', '2024-01-02', '2024-01-02', '2024-01-02',
        '2024-01-03', '2024-01-03'
    ],
    '상품': [
        '아이폰 14', '갤럭시 S23', '아이패드 프로', '아이폰 14',
        '아이폰 14', '갤럭시 S23', '아이패드 프로', '갤럭시 S23',
        '맥북 프로', '아이폰 14'
    ],
    '판매량': [15, 30, 5, 10, 20, 25, 10, 5, 8, 12],
    '가격': [1000, 900, 800, 1000, 1000, 900, 800, 900, 2000, 1000]
}
sale_df = pd.DataFrame(data)
sale_df

           날짜       상품  판매량    가격
0  2024-01-01   아이폰 14   15  1000
1  2024-01-01  갤럭시 S23   30   900
2  2024-01-01  아이패드 프로    5   800
3  2024-01-01   아이폰 14   10  1000
4  2024-01-02   아이폰 14   20  1000
5  2024-01-02  갤럭시 S23   25   900
6  2024-01-02  아이패드 프로   10   800
7  2024-01-02  갤럭시 S23    5   900
8  2024-01-03    맥북 프로    8  2000
9  2024-01-03   아이폰 14   12  1000

In [26]:
# pivot_table
sale_pibot_df = pd.pivot_table(
    sale_df,
    index='날짜', # 행 기준을 날짜로 설정
    columns='상품', # 열 기준을 상품으로 설정
    values='판매량', # 표 안에 채울 값
    fill_value=0, # 값이 없는 조합은 0으로 채움
    aggfunc='sum', # 같은 날짜/상품이 여러 개면 판매량을 합산
    margins=True # 행/열 합계 추가
)

sale_pibot_df

상품          갤럭시 S23  맥북 프로  아이패드 프로  아이폰 14  All
날짜
2024-01-01       30      0        5      25   60
2024-01-02       30      0       10      20   60
2024-01-03        0      8        0      12   20
All              60      8       15      57  140

### 타이타닉 데이터셋

In [28]:
titanic_df = pd.read_csv('./data/titanic.csv')
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [29]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [30]:
# 성별, 선실등급별 생존율 조회
pd.pivot_table(
    titanic_df,
    index='Pclass',
    columns='Sex',
    values='Survived',
    aggfunc='mean',
    margins=True
).round(2)

Sex     female  male   All
Pclass
1         0.97  0.37  0.63
2         0.92  0.16  0.47
3         0.50  0.14  0.24
All       0.74  0.19  0.38